name: Alfred Workflow Release Action

on:
  push:
    tags: ["*"]

env:
  WORKFLOW_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Changelog
        run: |
          count_tags="$(git tag | wc -l)"
          if [[ $count_tags -ge 2 ]]; then # requires 2 tags
            previous_tag="$(git tag --sort=-creatordate | head -3 | tail -1)" 
            ref="$previous_tag"
          else
            root_commit="$(git rev-list --max-parents=0 HEAD)"
            ref="$root_commit"
          fi
          prev_commit_messages="$(git log "${ref}"..HEAD --pretty='format:- %s.')"
          echo "$prev_commit_messages"
          echo "# Changelog" > CHANGELOG.txt
          echo "## ref: $ref" >> CHANGELOG.txt
          echo "git tags: $(git tag --list)" >> CHANGELOG.txt
          echo "git log: $(git log --pretty=oneline)" >> CHANGELOG.txt
          echo "$prev_commit_messages" >> CHANGELOG.txt

      - name: Build .alfredworkflow
        run: |
          zip --quiet --recurse-paths "${{ env.WORKFLOW_NAME }}.alfredworkflow" . \
            --exclude ".git*" "Makefile" ".build-and-release.sh" "README.md" "assets/*" \
            ".DS_Store" ".rsync-exclude"

      # DOCS https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ env.GITHUB_TOKEN }}
          body_path: CHANGELOG.txt
          files: ${{ env.WORKFLOW_NAME }}.alfredworkflow
